spring:
  application:
    name: country-currency-webclient-client

server:
  port: ${PORT:0}   # 8200    # 8201   # 8202



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
  client:
    #    serviceUrl:
    #      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5


